export const DELIVERY_TYPE = {
  DOOR_DOOR: 'DOOR_DOOR',
  STATION_STATION: 'STATION_STATION',
  DOOR_STATION: 'DOOR_STATION',
  STATION_DOOR: 'STATION_DOOR',
//   ACCEPTED: 'ACCEPTED',
//   REJECTED: 'REJECTED',
//   DECLINED: 'DECLINED',
//   ARRIVED: 'ARRIVED',
//   OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
//   DELIVERED: 'DELIVERED',
//   FAILED: 'FAILED',
//   CANCELLED: 'CANCELLED',
} as const;