export const DELIVERY_STATUS = {
  CREATED: 'CREATED',
  SCHEDULED: 'SCHEDULED',
  ASSIGNED: 'ASSIGNED',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
} as const;